#!/usr/bin/env bash

cmd_help() {
  echo "Usage: gitpack <command>"
  echo ""
  echo "Commands:"
  echo "    gitpack install [app]  -  Install an app"
  echo "    gitpack remove [app]   -  Remove an app"
  echo "    gitpack run [app] %    -  Update and run an app. Additional arguments are passed through to the app"
  echo "    gitpack update         -  Update gitpack itself"
  echo ""
}

cmd_install() {
  # should install gitpack itself first (it not already installed)
  # clones the project repo
  # generates a file in .local/bin that calls gitpack run [app]
  echo "cmd_install: $1"
}

cmd_remove() {
  echo "cmd_remove: $1"
}

cmd_run() {
  echo "cmd_run: $1"
}

cmd_update() {
  echo "cmd_update"
}

case "$1" in
help) cmd_help ;;
install) cmd_install "$2" ;;
remove) cmd_remove "$2" ;;
run) cmd_run "$2" ;;
update) cmd_update ;;
*)
  echo "Unknown command: $1"
  echo "Run gitpack help for usage instructions"
  exit 1
  ;;
esac
